kind: ImageStreamTag
apiVersion: image.openshift.io/v1
metadata:
  name: hello-world:{{ image_tag }}
  namespace: demo-prod
tag:
  name: 'hello-world:{{ image_tag }}'
  annotations:
  from:
    kind: ImageStreamTag
    namespace: demo-test
    name: hello-world:{{ image_tag }}
  generation:
  importPolicy: {}
  referencePolicy:
    type: Source
generation: 0
lookupPolicy:
  local: false
image:
  metadata:
    creationTimestamp:
  dockerImageMetadata:
  dockerImageLayers: