---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansible
  namespace: aap
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
subjects:
  - kind: ServiceAccount
    name: ansible
    namespace: aap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin