---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
  name: event-listener-hello-github
  namespace: demo-test
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-hello-github