---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: timestamp-task
  namespace: demo-test
spec:
  results:
    - name: current-date-unix-timestamp
      description: The current date in unix timestamp format
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      command:
        - /bin/bash
        - '-c'
        - date +%s | tee $(results.current-date-unix-timestamp.path)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aap-launch-workflow
  namespace: demo-test
spec:
  params:
    - name: baseUrl
      type: string
    - name: workflowId
      type: string
    - name: username
      type: string
    - name: password
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - >-
          curl -k -X POST --user
          $(inputs.params.username):$(inputs.params.password)
          $(inputs.params.baseUrl)/api/v2/workflow_job_templates/$(inputs.params.workflowId)/launch/
      image: registry.redhat.io/ubi7/ubi-minimal
      name: launch-workflow