---
- hosts: localhost
  collections:
  - kubernetes.core

  tasks:
  - name: create k8s pipeline task
    kubernetes.core.k8s:
      src: ../openshift-resources/openshift-timestamp-task.yaml
      state: present
  
  - name: create k8s pipeline task
    kubernetes.core.k8s:
      src: ../openshift-resources/openshift-aap-api-task.yaml
      state: present

  - name: create k8s pipeline
    kubernetes.core.k8s:
      src: ../openshift-resources/openshift-pipeline.yaml
      state: present

  - name: create k8s pipeline triggers listener
    kubernetes.core.k8s:
      src: ../openshift-resources/openshift-pipeline-triggers-listener.yaml
      state: present
      

  - name: create k8s pipeline triggers template
    kubernetes.core.k8s:
      src: ../openshift-resources/openshift-pipeline-triggers-template.yaml
      state: present

    - name: create k8s pipeline triggers template
    kubernetes.core.k8s:
      definition: "{{ lookup('template', '../openshift-resources/openshift-secret-aap-creds.yaml') | from_yaml }}"
      state: present