---
- hosts: localhost
  collections:
  - kubernetes.core

  tasks:
  - name: create k8s pipeline tasks
    kubernetes.core.k8s:
      src: ../openshift-resources/openshift-timestamp-task.yaml
      state: present

  - name: create k8s pipeline
    kubernetes.core.k8s:
      definition: "{{ lookup('file', '../openshift-resources/openshift-pipeline.yaml') | from_yaml_all }}"
      state: present
