---
- hosts: localhost
  collections:
  - kubernetes.core

  tasks:
  - name: create k8s pipeline task
    kubernetes.core.k8s:
      src: ../openshift-resources/openshift-timestamp-task.yaml
      state: present
  
  - name: create k8s pipeline task
    kubernetes.core.k8s:
      src: ../openshift-resources/openshift-aap-api-task.yaml
      state: present

  - name: create k8s pipeline
    kubernetes.core.k8s:
      definition: "{{ lookup('file', '../openshift-resources/openshift-pipeline.yaml') | from_yaml_all }}"
      state: present

  - name: create k8s pipeline triggers
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', '../openshift-resources/openshift-pipeline-triggers.yaml') | from_yaml_all }}"