---
- hosts: localhost
  collections:
  - kubernetes.core

  tasks:
  - name: create deployment
    register: image_tag
    kubernetes.core.k8s:
      src: ../openshift-resources/app-hello-deployment.yaml
      state: present
